### ISSUE TITLE
[Selenium IDE 2.0.0] Failed to load sideflow.js

### ISSUE THREAD

**Issue by gssjr** [73rhodes/sideflow#7]
I receive the following error:

Selenium IDE 2.0.0
Firefox 22.0
sideflow.js -- from commit c71d9f904182a6683b9fbbb4a982990f1779f2d3

[JavaScript Application]

Failed to load user-extensions.js!
files=/Users/gregory.santone/SeleniumIDE plugins/sideflow.js
lineNumber=4
error=SyntaxError: syntax error

**Comment by shijingshijing** [comment]
I signed up for the only purpose to condemn the stupid fxxking github URI design. I spend a whole afternoon to figure out what's going wrong and I was totally fxxked by downloading this js file directly via the URL [https://github.com/darrenderidder/sideflow/blob/master/sideflow.js], my firefox keeps prompting me "SyntaxError" and failed to load user-extensions.js. The URI like [https://github.com/darrenderidder/sideflow/blob/master/sideflow.js] shall only be direct to a JS file rather than a WebPage. this damn stupid design of GitHub shall be condemned.
